//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenciaServicio
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicio.SolicitudCambioClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicio.SolicitudRecuperarClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicio.SolicitudCredenciales))]
    public partial class SolicitudBase : object
    {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCambioClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudCambioClave : ReferenciaServicio.SolicitudBase
    {
        
        private string ClaveAntiguaField;
        
        private string ClaveNuevaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveAntigua
        {
            get
            {
                return this.ClaveAntiguaField;
            }
            set
            {
                this.ClaveAntiguaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveNueva
        {
            get
            {
                return this.ClaveNuevaField;
            }
            set
            {
                this.ClaveNuevaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudRecuperarClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudRecuperarClave : ReferenciaServicio.SolicitudBase
    {
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCredenciales", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudCredenciales : ReferenciaServicio.SolicitudBase
    {
        
        private string ClaveField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicio.RespuestaRecuperarClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicio.RespuestaCredenciales))]
    public partial class RespuestaBase : object
    {
        
        private bool ExitoField;
        
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRecuperarClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaRecuperarClave : ReferenciaServicio.RespuestaBase
    {
        
        private string ClaveRecuperadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveRecuperada
        {
            get
            {
                return this.ClaveRecuperadaField;
            }
            set
            {
                this.ClaveRecuperadaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCredenciales", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaCredenciales : ReferenciaServicio.RespuestaBase
    {
        
        private string TokenGeneradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenGenerado
        {
            get
            {
                return this.TokenGeneradoField;
            }
            set
            {
                this.TokenGeneradoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicio.IServicioAutenticacion")]
    public interface IServicioAutenticacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/ValidarCredenciales", ReplyAction="http://tempuri.org/IServicioAutenticacion/ValidarCredencialesResponse")]
        System.Threading.Tasks.Task<ReferenciaServicio.ValidarCredencialesResponse> ValidarCredencialesAsync(ReferenciaServicio.ValidarCredencialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/CambiarContrasena", ReplyAction="http://tempuri.org/IServicioAutenticacion/CambiarContrasenaResponse")]
        System.Threading.Tasks.Task<ReferenciaServicio.CambiarContrasenaResponse> CambiarContrasenaAsync(ReferenciaServicio.CambiarContrasenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/RecuperarContrasena", ReplyAction="http://tempuri.org/IServicioAutenticacion/RecuperarContrasenaResponse")]
        System.Threading.Tasks.Task<ReferenciaServicio.RecuperarContrasenaResponse> RecuperarContrasenaAsync(ReferenciaServicio.RecuperarContrasenaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarCredenciales", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarCredencialesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.SolicitudCredenciales solicitud;
        
        public ValidarCredencialesRequest()
        {
        }
        
        public ValidarCredencialesRequest(ReferenciaServicio.SolicitudCredenciales solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarCredencialesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarCredencialesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.RespuestaCredenciales ValidarCredencialesResult;
        
        public ValidarCredencialesResponse()
        {
        }
        
        public ValidarCredencialesResponse(ReferenciaServicio.RespuestaCredenciales ValidarCredencialesResult)
        {
            this.ValidarCredencialesResult = ValidarCredencialesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarContrasena", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CambiarContrasenaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.SolicitudCambioClave solicitud;
        
        public CambiarContrasenaRequest()
        {
        }
        
        public CambiarContrasenaRequest(ReferenciaServicio.SolicitudCambioClave solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarContrasenaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CambiarContrasenaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.RespuestaBase CambiarContrasenaResult;
        
        public CambiarContrasenaResponse()
        {
        }
        
        public CambiarContrasenaResponse(ReferenciaServicio.RespuestaBase CambiarContrasenaResult)
        {
            this.CambiarContrasenaResult = CambiarContrasenaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarContrasena", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarContrasenaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.SolicitudRecuperarClave solicitud;
        
        public RecuperarContrasenaRequest()
        {
        }
        
        public RecuperarContrasenaRequest(ReferenciaServicio.SolicitudRecuperarClave solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarContrasenaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperarContrasenaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicio.RespuestaRecuperarClave RecuperarContrasenaResult;
        
        public RecuperarContrasenaResponse()
        {
        }
        
        public RecuperarContrasenaResponse(ReferenciaServicio.RespuestaRecuperarClave RecuperarContrasenaResult)
        {
            this.RecuperarContrasenaResult = RecuperarContrasenaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioAutenticacionChannel : ReferenciaServicio.IServicioAutenticacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioAutenticacionClient : System.ServiceModel.ClientBase<ReferenciaServicio.IServicioAutenticacion>, ReferenciaServicio.IServicioAutenticacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAutenticacionClient() : 
                base(ServicioAutenticacionClient.GetDefaultBinding(), ServicioAutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioAutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicio.ValidarCredencialesResponse> ValidarCredencialesAsync(ReferenciaServicio.ValidarCredencialesRequest request)
        {
            return base.Channel.ValidarCredencialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicio.CambiarContrasenaResponse> CambiarContrasenaAsync(ReferenciaServicio.CambiarContrasenaRequest request)
        {
            return base.Channel.CambiarContrasenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicio.RecuperarContrasenaResponse> RecuperarContrasenaAsync(ReferenciaServicio.RecuperarContrasenaRequest request)
        {
            return base.Channel.RecuperarContrasenaAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57487/ServicioAutenticacion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAutenticacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioAutenticacion,
        }
    }
}
