//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAutenticacionRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioAutenticacionRef.SolicitudCambioClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioAutenticacionRef.SolicitudRecuperarClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioAutenticacionRef.SolicitudCredenciales))]
    public partial class SolicitudBase : object
    {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCambioClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudCambioClave : ServicioAutenticacionRef.SolicitudBase
    {
        
        private string ClaveAntiguaField;
        
        private string ClaveNuevaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveAntigua
        {
            get
            {
                return this.ClaveAntiguaField;
            }
            set
            {
                this.ClaveAntiguaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveNueva
        {
            get
            {
                return this.ClaveNuevaField;
            }
            set
            {
                this.ClaveNuevaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudRecuperarClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudRecuperarClave : ServicioAutenticacionRef.SolicitudBase
    {
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCredenciales", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudCredenciales : ServicioAutenticacionRef.SolicitudBase
    {
        
        private string ClaveField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioAutenticacionRef.RespuestaRecuperarClave))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioAutenticacionRef.RespuestaCredenciales))]
    public partial class RespuestaBase : object
    {
        
        private bool ExitoField;
        
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRecuperarClave", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaRecuperarClave : ServicioAutenticacionRef.RespuestaBase
    {
        
        private string ClaveRecuperadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveRecuperada
        {
            get
            {
                return this.ClaveRecuperadaField;
            }
            set
            {
                this.ClaveRecuperadaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCredenciales", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaCredenciales : ServicioAutenticacionRef.RespuestaBase
    {
        
        private string TokenGeneradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenGenerado
        {
            get
            {
                return this.TokenGeneradoField;
            }
            set
            {
                this.TokenGeneradoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioAutenticacionRef.IServicioAutenticacion")]
    public interface IServicioAutenticacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/ValidarCredenciales", ReplyAction="http://tempuri.org/IServicioAutenticacion/ValidarCredencialesResponse")]
        System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaCredenciales> ValidarCredencialesAsync(ServicioAutenticacionRef.SolicitudCredenciales solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/CambiarContrasena", ReplyAction="http://tempuri.org/IServicioAutenticacion/CambiarContrasenaResponse")]
        System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaBase> CambiarContrasenaAsync(ServicioAutenticacionRef.SolicitudCambioClave solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutenticacion/RecuperarContrasena", ReplyAction="http://tempuri.org/IServicioAutenticacion/RecuperarContrasenaResponse")]
        System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaRecuperarClave> RecuperarContrasenaAsync(ServicioAutenticacionRef.SolicitudRecuperarClave solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioAutenticacionChannel : ServicioAutenticacionRef.IServicioAutenticacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioAutenticacionClient : System.ServiceModel.ClientBase<ServicioAutenticacionRef.IServicioAutenticacion>, ServicioAutenticacionRef.IServicioAutenticacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAutenticacionClient() : 
                base(ServicioAutenticacionClient.GetDefaultBinding(), ServicioAutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), ServicioAutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaCredenciales> ValidarCredencialesAsync(ServicioAutenticacionRef.SolicitudCredenciales solicitud)
        {
            return base.Channel.ValidarCredencialesAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaBase> CambiarContrasenaAsync(ServicioAutenticacionRef.SolicitudCambioClave solicitud)
        {
            return base.Channel.CambiarContrasenaAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServicioAutenticacionRef.RespuestaRecuperarClave> RecuperarContrasenaAsync(ServicioAutenticacionRef.SolicitudRecuperarClave solicitud)
        {
            return base.Channel.RecuperarContrasenaAsync(solicitud);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57487/ServicioAutenticacion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAutenticacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioAutenticacion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioAutenticacion,
        }
    }
}
