//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferenciaServicioConversion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicioConversion.SolicitudValidarNumerico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicioConversion.SolicitudConversion))]
    public partial class SolicitudBase : object
    {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudValidarNumerico", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudValidarNumerico : ReferenciaServicioConversion.SolicitudBase
    {
        
        private string ValorStrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorStr
        {
            get
            {
                return this.ValorStrField;
            }
            set
            {
                this.ValorStrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudConversion", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class SolicitudConversion : ReferenciaServicioConversion.SolicitudBase
    {
        
        private string UnidadDestinoField;
        
        private string UnidadOrigenField;
        
        private double ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino
        {
            get
            {
                return this.UnidadDestinoField;
            }
            set
            {
                this.UnidadDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen
        {
            get
            {
                return this.UnidadOrigenField;
            }
            set
            {
                this.UnidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicioConversion.RespuestaValidarNumerico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ReferenciaServicioConversion.RespuestaConversion))]
    public partial class RespuestaBase : object
    {
        
        private bool ExitoField;
        
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaValidarNumerico", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaValidarNumerico : ReferenciaServicioConversion.RespuestaBase
    {
        
        private bool EsValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido
        {
            get
            {
                return this.EsValidoField;
            }
            set
            {
                this.EsValidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConversion", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF")]
    public partial class RespuestaConversion : ReferenciaServicioConversion.RespuestaBase
    {
        
        private double ValorConvertidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertido
        {
            get
            {
                return this.ValorConvertidoField;
            }
            set
            {
                this.ValorConvertidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaServicioConversion.IServicioConversion")]
    public interface IServicioConversion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirLongitud", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirLongitudResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirLongitudResponse> ConvertirLongitudAsync(ReferenciaServicioConversion.ConvertirLongitudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirTemperatura", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirTemperaturaResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirTemperaturaResponse> ConvertirTemperaturaAsync(ReferenciaServicioConversion.ConvertirTemperaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirMasa", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirMasaResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirMasaResponse> ConvertirMasaAsync(ReferenciaServicioConversion.ConvertirMasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ValidarCampoNumerico", ReplyAction="http://tempuri.org/IServicioConversion/ValidarCampoNumericoResponse")]
        System.Threading.Tasks.Task<ReferenciaServicioConversion.ValidarCampoNumericoResponse> ValidarCampoNumericoAsync(ReferenciaServicioConversion.ValidarCampoNumericoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirLongitud", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirLongitudRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.SolicitudConversion solicitud;
        
        public ConvertirLongitudRequest()
        {
        }
        
        public ConvertirLongitudRequest(ReferenciaServicioConversion.SolicitudConversion solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirLongitudResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirLongitudResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.RespuestaConversion ConvertirLongitudResult;
        
        public ConvertirLongitudResponse()
        {
        }
        
        public ConvertirLongitudResponse(ReferenciaServicioConversion.RespuestaConversion ConvertirLongitudResult)
        {
            this.ConvertirLongitudResult = ConvertirLongitudResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirTemperatura", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirTemperaturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.SolicitudConversion solicitud;
        
        public ConvertirTemperaturaRequest()
        {
        }
        
        public ConvertirTemperaturaRequest(ReferenciaServicioConversion.SolicitudConversion solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirTemperaturaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirTemperaturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.RespuestaConversion ConvertirTemperaturaResult;
        
        public ConvertirTemperaturaResponse()
        {
        }
        
        public ConvertirTemperaturaResponse(ReferenciaServicioConversion.RespuestaConversion ConvertirTemperaturaResult)
        {
            this.ConvertirTemperaturaResult = ConvertirTemperaturaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirMasa", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirMasaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.SolicitudConversion solicitud;
        
        public ConvertirMasaRequest()
        {
        }
        
        public ConvertirMasaRequest(ReferenciaServicioConversion.SolicitudConversion solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConvertirMasaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ConvertirMasaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.RespuestaConversion ConvertirMasaResult;
        
        public ConvertirMasaResponse()
        {
        }
        
        public ConvertirMasaResponse(ReferenciaServicioConversion.RespuestaConversion ConvertirMasaResult)
        {
            this.ConvertirMasaResult = ConvertirMasaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarCampoNumerico", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarCampoNumericoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.SolicitudValidarNumerico solicitud;
        
        public ValidarCampoNumericoRequest()
        {
        }
        
        public ValidarCampoNumericoRequest(ReferenciaServicioConversion.SolicitudValidarNumerico solicitud)
        {
            this.solicitud = solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidarCampoNumericoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidarCampoNumericoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ReferenciaServicioConversion.RespuestaValidarNumerico ValidarCampoNumericoResult;
        
        public ValidarCampoNumericoResponse()
        {
        }
        
        public ValidarCampoNumericoResponse(ReferenciaServicioConversion.RespuestaValidarNumerico ValidarCampoNumericoResult)
        {
            this.ValidarCampoNumericoResult = ValidarCampoNumericoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioConversionChannel : ReferenciaServicioConversion.IServicioConversion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioConversionClient : System.ServiceModel.ClientBase<ReferenciaServicioConversion.IServicioConversion>, ReferenciaServicioConversion.IServicioConversion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioConversionClient() : 
                base(ServicioConversionClient.GetDefaultBinding(), ServicioConversionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioConversion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), ServicioConversionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirLongitudResponse> ConvertirLongitudAsync(ReferenciaServicioConversion.ConvertirLongitudRequest request)
        {
            return base.Channel.ConvertirLongitudAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirTemperaturaResponse> ConvertirTemperaturaAsync(ReferenciaServicioConversion.ConvertirTemperaturaRequest request)
        {
            return base.Channel.ConvertirTemperaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioConversion.ConvertirMasaResponse> ConvertirMasaAsync(ReferenciaServicioConversion.ConvertirMasaRequest request)
        {
            return base.Channel.ConvertirMasaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ReferenciaServicioConversion.ValidarCampoNumericoResponse> ValidarCampoNumericoAsync(ReferenciaServicioConversion.ValidarCampoNumericoRequest request)
        {
            return base.Channel.ValidarCampoNumericoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConversion))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConversion))
            {
                return new System.ServiceModel.EndpointAddress("https://server_soap.dr00p3r.top/Controlador/ServicioConversion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioConversionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioConversion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioConversionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioConversion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioConversion,
        }
    }
}
