//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioConversionRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioConversionRef.SolicitudValidarNumerico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioConversionRef.SolicitudConversion))]
    public partial class SolicitudBase : object
    {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudValidarNumerico", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    public partial class SolicitudValidarNumerico : ServicioConversionRef.SolicitudBase
    {
        
        private string ValorStrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorStr
        {
            get
            {
                return this.ValorStrField;
            }
            set
            {
                this.ValorStrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudConversion", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    public partial class SolicitudConversion : ServicioConversionRef.SolicitudBase
    {
        
        private string UnidadDestinoField;
        
        private string UnidadOrigenField;
        
        private double ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadDestino
        {
            get
            {
                return this.UnidadDestinoField;
            }
            set
            {
                this.UnidadDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadOrigen
        {
            get
            {
                return this.UnidadOrigenField;
            }
            set
            {
                this.UnidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaBase", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioConversionRef.RespuestaValidarNumerico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServicioConversionRef.RespuestaConversion))]
    public partial class RespuestaBase : object
    {
        
        private bool ExitoField;
        
        private string MensajeErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito
        {
            get
            {
                return this.ExitoField;
            }
            set
            {
                this.ExitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaValidarNumerico", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    public partial class RespuestaValidarNumerico : ServicioConversionRef.RespuestaBase
    {
        
        private bool EsValidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido
        {
            get
            {
                return this.EsValidoField;
            }
            set
            {
                this.EsValidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaConversion", Namespace="http://schemas.datacontract.org/2004/07/ConversionesServerWCF.Modelo")]
    public partial class RespuestaConversion : ServicioConversionRef.RespuestaBase
    {
        
        private double ValorConvertidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ValorConvertido
        {
            get
            {
                return this.ValorConvertidoField;
            }
            set
            {
                this.ValorConvertidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioConversionRef.IServicioConversion")]
    public interface IServicioConversion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirLongitud", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirLongitudResponse")]
        System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirLongitudAsync(ServicioConversionRef.SolicitudConversion solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirTemperatura", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirTemperaturaResponse")]
        System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirTemperaturaAsync(ServicioConversionRef.SolicitudConversion solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ConvertirMasa", ReplyAction="http://tempuri.org/IServicioConversion/ConvertirMasaResponse")]
        System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirMasaAsync(ServicioConversionRef.SolicitudConversion solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConversion/ValidarCampoNumerico", ReplyAction="http://tempuri.org/IServicioConversion/ValidarCampoNumericoResponse")]
        System.Threading.Tasks.Task<ServicioConversionRef.RespuestaValidarNumerico> ValidarCampoNumericoAsync(ServicioConversionRef.SolicitudValidarNumerico solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioConversionChannel : ServicioConversionRef.IServicioConversion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioConversionClient : System.ServiceModel.ClientBase<ServicioConversionRef.IServicioConversion>, ServicioConversionRef.IServicioConversion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioConversionClient() : 
                base(ServicioConversionClient.GetDefaultBinding(), ServicioConversionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioConversion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), ServicioConversionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioConversionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioConversionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirLongitudAsync(ServicioConversionRef.SolicitudConversion solicitud)
        {
            return base.Channel.ConvertirLongitudAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirTemperaturaAsync(ServicioConversionRef.SolicitudConversion solicitud)
        {
            return base.Channel.ConvertirTemperaturaAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServicioConversionRef.RespuestaConversion> ConvertirMasaAsync(ServicioConversionRef.SolicitudConversion solicitud)
        {
            return base.Channel.ConvertirMasaAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServicioConversionRef.RespuestaValidarNumerico> ValidarCampoNumericoAsync(ServicioConversionRef.SolicitudValidarNumerico solicitud)
        {
            return base.Channel.ValidarCampoNumericoAsync(solicitud);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConversion))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioConversion))
            {
                return new System.ServiceModel.EndpointAddress("https://server_soap.dr00p3r.top/Controlador/ServicioConversion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioConversionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioConversion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioConversionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioConversion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioConversion,
        }
    }
}
